# Generated by Django 4.1.1 on 2022-10-16 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="título de la categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="files",
                        verbose_name="archivo adjunto",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "comentario",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                ("content", models.TextField(verbose_name="contenido")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Pendiente"),
                            (2, "Aprobado"),
                            (3, "En curso"),
                            (4, "Finalizado"),
                        ],
                        default=1,
                        verbose_name="estado",
                    ),
                ),
                (
                    "urgency",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Urgente"),
                            (2, "Alta"),
                            (3, "Media"),
                            (4, "Baja"),
                        ],
                        default=3,
                        verbose_name="urgencia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="último cambio"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="agente",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.category",
                    ),
                ),
                (
                    "comments",
                    models.ManyToManyField(
                        related_name="comments", to="tickets.comment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
            },
        ),
    ]
