# Generated by Django 4.1.1 on 2022-10-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="file",
            field=models.ImageField(
                blank=True, null=True, upload_to="files", verbose_name="archivo adjunto"
            ),
        ),
    ]
