# Generated by Django 4.1.1 on 2022-10-16 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tickets.category",
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="comments",
            field=models.ManyToManyField(
                related_name="comments",
                to="tickets.comment",
                verbose_name="comentarios",
            ),
        ),
    ]
