# Generated by Django 4.1.1 on 2022-10-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_ticket_category_alter_ticket_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Pendiente"),
                    (2, "Aprobado"),
                    (3, "En curso"),
                    (4, "Finalizado"),
                    (5, "Rechazado"),
                ],
                default=1,
                verbose_name="estado",
            ),
        ),
    ]
