# Generated by Django 4.1.1 on 2022-10-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="comments",
            field=models.ManyToManyField(
                blank=True,
                related_name="comments",
                to="tickets.comment",
                verbose_name="comentarios",
            ),
        ),
    ]
