# Generated by Django 4.1.1 on 2022-10-23 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_ticket_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"], "verbose_name": "comentario"},
        ),
    ]
