# Generated by Django 4.1.1 on 2022-10-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="comments",
        ),
        migrations.AddField(
            model_name="comment",
            name="ticket",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_comments",
                to="tickets.ticket",
                verbose_name="ticket",
            ),
            preserve_default=False,
        ),
    ]
