# Generated by Django 4.1.1 on 2022-11-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_remove_ticket_comments_comment_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Pendiente"),
                    (2, "En curso"),
                    (3, "Finalizado"),
                    (4, "Rechazado"),
                ],
                default=1,
                verbose_name="estado",
            ),
        ),
    ]
