# Generated by Django 4.1.1 on 2022-11-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticket_options_ticket_rejection_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_category',
            field=models.CharField(max_length=5000, null=True, verbose_name='subcategoria'),
        ),
    ]
