# Generated by Django 4.1.1 on 2022-11-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('', '---------'), ('PRENSA', 'Prensa y Redacción'), ('AUDIOVISUAL', 'Audiovisual'), ('DISENHO', 'Diseño Grafico'), ('WEB', 'Web')], default='', max_length=50, verbose_name='categoria'),
        ),
    ]
