# Generated by Django 4.1.1 on 2022-11-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0012_alter_ticket_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    (None, "---------"),
                    ("PRENSA", "Prensa y Redacción"),
                    ("AUDIOVISUAL", "Audiovisual"),
                    ("DISENHO", "Diseño Grafico"),
                    ("WEB", "Web"),
                ],
                default="",
                max_length=50,
                verbose_name="categoria",
            ),
        ),
    ]
