# Generated by Django 4.1.1 on 2022-11-30 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0013_delete_category_alter_ticket_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="email",
        ),
    ]
