# Generated by Django 4.1.1 on 2022-09-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gov_id",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="documento de identidad"
            ),
        ),
    ]
