# Generated by Django 4.1.1 on 2022-09-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_gov_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "usuario"},
        ),
    ]
