# Generated by Django 4.1.1 on 2022-09-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Director"), (2, "Analista"), (3, "Cliente")],
                default=3,
                verbose_name="rol",
            ),
        ),
    ]
