# Generated by Django 4.1.1 on 2022-09-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Director"),
                    (2, "Analista"),
                    (3, "Cliente"),
                    (4, "Técnico"),
                ],
                default=3,
                verbose_name="rol",
            ),
        ),
    ]
