# Generated by Django 4.1.1 on 2022-12-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_persona_area_persona_dependency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="dependency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Rectorado - Gabinete"),
                    ("2", "Vice Rectorado"),
                    ("3", "Rectorado - Secretaria General"),
                    ("4", "Rectorado - Asesoría Jurídica"),
                    ("5", "Rectorado - Auditoría General"),
                    ("6", "Rectorado - DGA"),
                    ("7", "Rectorado - DGAyF"),
                    ("8", "Rectorado - DGEU"),
                    ("9", "Rectorado - DGICT"),
                    ("10", "Rectorado - DGGyTH"),
                    ("11", "Rectorado - DGOTI"),
                    ("12", "Rectorado - DGPD"),
                    ("13", "Rectorado - DGP"),
                    ("14", "Rectorado - DGPRI"),
                    ("35", "UA - FACSO"),
                    ("36", "Rectorado - DRIC"),
                    ("37", "Rectorado - Informatica"),
                    ("38", "Rectorado - Transparencia"),
                    ("15", "CNC - UNA"),
                    ("16", "CNEA - UNA"),
                    ("17", "CEMIT - UNA"),
                    ("18", "CETTRI - UNA"),
                    ("19", "IICS - UNA"),
                    ("39", "CEVUNA"),
                    ("20", "Biblioteca Central"),
                    ("21", "INCUNA"),
                    ("22", "UA - FDCS"),
                    ("23", "UA - FCM"),
                    ("24", "UA - FI"),
                    ("25", "UA - FCE"),
                    ("26", "UA - FO"),
                    ("27", "UA - FCQ"),
                    ("28", "UA - FCA"),
                    ("29", "UA - FF"),
                    ("30", "UA - FCV"),
                    ("31", "UA - FADA"),
                    ("32", "UA - FP"),
                    ("33", "UA - FACEN"),
                    ("34", "UA - FENOB"),
                ],
                max_length=2,
                null=True,
                verbose_name="dependencia",
            ),
        ),
    ]
